version: '3.8'

services:
  web:
    build: .
    container_name: react-app-profissa
    env_file:        # <--- Adicione isso
      - .env         # <--- Isso faz o Docker ler seu arquivo .env
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Garante que o Hot Reload funcione no Windows/WSL
    restart: always