name: Docker CI/CD

on:
  push:
    branches: [ "main" ] # Executa toda vez que você enviar código para a main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build da Imagem Docker
        run: docker build -t meu-usuario/meu-projeto-react:latest .

      - name: Rodar Testes
        run: echo "Aqui você rodaria seus testes automatizados"

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da Imagem
        run: docker build -t gustavoferreira/mojito_project:latest .

      - name: Push da Imagem
        run: docker push gustavoferreira/mojito_project:latest